import './styles-v2.css';
import { hasSupabaseConfig, supabase } from './supabaseClient.js';
import { STATUSES, NAV_ITEMS, STARTER_LISTINGS } from './data.js';

const $ = (s) => document.querySelector(s);
const app = $('#app');
const ACCESS_CODE = String(import.meta.env.VITE_AWR_ACCESS_CODE || 'home').trim();
const USERS = ['Stephen', 'Stephanie'];
let listings = [], view = 'dashboard', editing = null, q = '', filter = 'All', toast = '', toastTimer = null;

init();

async function init(){
  if(!hasSupabaseConfig){listings=STARTER_LISTINGS.map(x=>({...x,id:crypto.randomUUID()})); draw(); return;}
  if(accessOk()) await load();
  draw();
}

async function load(returnData=false){
  const {data,error}=await supabase.from('apartments').select('*').order('is_crossed_off',{ascending:true}).order('status',{ascending:true}).order('score',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false});
  if(error){say(error.message); return returnData?[]:undefined;}
  if(returnData) return data||[]; listings=data||[];
}

function draw(){
  const active=listings.filter(x=>!crossed(x)), hist=listings.filter(crossed);
  app.innerHTML=`<main class="shell">
    <section class="hero-card"><div class="eyebrow">Apartment Search</div><h1>Apartment<br>War Room</h1><p>Shared decision board for Stephen & Stephanie. Track leads, calls, tours, screenshots, and final contenders.</p><div class="hero-stats">${stat('Active',active.length)}${stat('To Call',count('To Call'))}${stat('Finalists',count('Finalist'))}${stat('History',hist.length)}</div></section>
    ${auth()}
    <section class="content-card">${head()}${body()}</section>
    ${toast?`<div class="toast">${esc(toast)}</div>`:''}
    <nav class="bottom-nav">${NAV_ITEMS.map(n=>`<button class="${view===n.id?'active':''}" data-view="${n.id}"><span>${n.icon}</span>${n.label}</button>`).join('')}</nav>
  </main>`;
  bind();
}

function stat(a,b){return `<div><span>${a}</span><strong>${b}</strong></div>`}
function accessOk(){return localStorage.getItem('awr_access_ok')==='true' && USERS.includes(currentUser())}
function currentUser(){return localStorage.getItem('awr_user')||''}
function can(){return !hasSupabaseConfig||accessOk()}
function auth(){
  if(!hasSupabaseConfig) return `<section class="auth-card demo"><div><strong>Demo mode</strong><p>Supabase env vars are missing.</p></div></section>`;
  if(accessOk()) return `<section class="auth-card household-card household-signed signed-in"><div><strong>${esc(currentUser())} is in the War Room</strong><p>Shared access is remembered on this device. No email links needed.</p></div><button class="ghost-button" data-act="logout">Switch / lock</button></section>`;
  return `<section class="auth-card household-card"><div><strong>Household access</strong><p>Pick your name, enter the shared code once, and this device will remember you.</p></div><div class="household-form"><select id="householdUser">${USERS.map(u=>`<option>${u}</option>`).join('')}</select><input id="accessCode" type="password" placeholder="Shared access code"><button data-act="login">Enter</button></div></section>`;
}
function head(){const t={dashboard:['Dashboard','Quick read on the search.'],listings:['Listings','Search, filter, edit, or remove active leads.'],add:[editing?'Edit Listing':'Add Listing',editing?'Update this lead.':'Add a new lead without clutter.'],history:['Crossed Off','Rejected and historical listings stay here.']}[view]; return `<div class="view-head"><div><h2>${t[0]}</h2><p>${t[1]}</p></div>${view!=='add'?'<button class="primary-button compact" data-act="new">+ Add</button>':''}</div>`}
function body(){if(!can())return `<div class="empty-state access-empty"><h3>Enter the shared code first</h3><p>After that, this device opens straight into the board as Stephen or Stephanie.</p></div>`; return view==='dashboard'?dashboard():view==='listings'?listView():view==='add'?form():history();}
function dashboard(){const hot=listings.filter(x=>!crossed(x)).sort((a,b)=>Number(b.score||0)-Number(a.score||0)).slice(0,3), finals=listings.filter(x=>x.status==='Finalist'&&!crossed(x)); return `<div class="dashboard-grid"><article class="mini-panel accent-panel"><span class="panel-label">Next action</span><h3>${listings.length?'Work the call list':'Load the starter board'}</h3><p>${listings.length?'Move serious leads into Contacted, Tour Scheduled, or Finalist.':'Seed the original War Room leads into Supabase once.'}</p><button class="primary-button" data-act="seed" ${listings.length?'disabled':''}>Load starter board</button></article><article class="mini-panel"><span class="panel-label">Top leads</span>${hot.length?hot.map(compact).join(''):'<p class="muted-copy">No leads yet.</p>'}</article><article class="mini-panel"><span class="panel-label">Finalists</span>${finals.length?finals.map(compact).join(''):'<p class="muted-copy">No finalists yet.</p>'}</article></div><div class="pipeline-strip">${STATUSES.map(s=>`<button class="pipeline-pill" data-filter="${s}"><span>${s}</span><strong>${count(s)}</strong></button>`).join('')}</div>`}
function compact(x){return `<button class="compact-lead" data-edit="${x.id}"><span>${esc(x.name)}</span><strong>${x.score??'—'}</strong></button>`}
function listView(){const rows=listings.filter(x=>!crossed(x)).filter(match).filter(x=>filter==='All'||x.status===filter); return `<div class="filters"><input id="search" type="search" placeholder="Search name, area, notes..." value="${esc(q)}"><select id="statusFilter"><option>All</option>${STATUSES.filter(s=>s!=='Crossed Off').map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="card-list">${rows.length?rows.map(card).join(''):empty('No active listings match','Try clearing the search or changing the filter.')}</div>`}
function history(){const rows=listings.filter(crossed).filter(match); return `<div class="filters single"><input id="search" type="search" placeholder="Search history..." value="${esc(q)}"></div><div class="card-list">${rows.length?rows.map(card).join(''):empty('No crossed-off listings','Rejected leads will live here instead of cluttering the active board.')}</div>`}
function card(x){const img=x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.name)}">`:`<div class="image-fallback"><span>${esc(x.status||'Lead')}</span><strong>${esc(x.tier||'War Room')}</strong></div>`;return `<article class="listing-card ${crossed(x)?'crossed':''}"><div class="listing-image">${img}</div><div class="listing-body"><div class="listing-topline"><div><h3>${esc(x.name)}</h3><p>${esc(x.area||x.address||'No area added')}</p></div><div class="score-badge"><span>Score</span><strong>${x.score??'—'}</strong></div></div><div class="price-line">${money(x.price)}</div><div class="chips"><span>${esc(x.status||'To Call')}</span>${x.tier?`<span>${esc(x.tier)}</span>`:''}${x.bedrooms?`<span>${x.bedrooms} bed</span>`:''}${x.bathrooms?`<span>${x.bathrooms} bath</span>`:''}${x.sqft?`<span>${x.sqft} sqft</span>`:''}</div>${x.notes?`<p class="notes">${esc(x.notes)}</p>`:''}${x.verify?`<details><summary>Verify</summary><p>${esc(x.verify)}</p></details>`:''}<div class="action-row">${x.source_url?`<a href="${esc(x.source_url)}" target="_blank" rel="noreferrer">Source</a>`:''}<button data-edit="${x.id}">Edit</button>${crossed(x)?`<button data-status="${x.id}" data-next="To Call">Restore</button>`:quick(x.id)}<button class="danger" data-del="${x.id}">Remove</button></div></div></article>`}
function quick(id){return `<button data-status="${id}" data-next="Contacted">Contacted</button><button data-status="${id}" data-next="Tour Scheduled">Tour</button><button data-status="${id}" data-next="Finalist">Finalist</button><button data-status="${id}" data-next="Crossed Off">Cross off</button>`}
function form(){const x=editing?listings.find(i=>i.id===editing):{};return `<form id="listingForm" class="listing-form"><div class="form-grid">${field('name','Name',x?.name,true)}${field('area','Area',x?.area)}${field('address','Address',x?.address)}${field('price','Price',x?.price,false,'number')}${field('bedrooms','Beds',x?.bedrooms,false,'number','0.5')}${field('bathrooms','Baths',x?.bathrooms,false,'number','0.5')}${field('sqft','Sqft',x?.sqft,false,'number')}${field('score','Score',x?.score,false,'number','0.1')}${field('tier','Tier',x?.tier)}<label>Status<select id="status">${STATUSES.map(s=>`<option ${x?.status===s?'selected':''}>${s}</option>`).join('')}</select></label>${field('source_url','Source URL',x?.source_url,false,'url')}${field('mls_number','MLS Number',x?.mls_number)}<label class="wide">Notes<textarea id="notes">${esc(x?.notes||'')}</textarea></label><label class="wide">Verify<textarea id="verify">${esc(x?.verify||'')}</textarea></label><label>Image / Screenshot<input id="imageFile" type="file" accept="image/*"></label><label class="check"><input id="is_crossed_off" type="checkbox" ${x?.is_crossed_off?'checked':''}> Crossed off</label></div><div class="form-actions"><button class="primary-button" type="submit">${editing?'Save changes':'Add listing'}</button><button class="ghost-button" type="button" data-act="clear">Clear</button>${editing?`<button class="danger-button" type="button" data-del="${editing}">Remove</button>`:''}</div></form>`}
function field(id,label,val='',req=false,type='text',step=''){return `<label>${label}<input id="${id}" type="${type}" value="${esc(val??'')}" ${step?`step="${step}"`:''} ${req?'required':''}></label>`}
function empty(a,b){return `<div class="empty-state"><h3>${a}</h3><p>${b}</p></div>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;if(view!=='add')editing=null;draw()});$('[data-act="login"]')?.addEventListener('click',login);$('#accessCode')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('[data-act="logout"]')?.addEventListener('click',logout);$('[data-act="seed"]')?.addEventListener('click',seed);$('[data-act="new"]')?.addEventListener('click',()=>{editing=null;view='add';draw()});$('[data-act="clear"]')?.addEventListener('click',()=>{editing=null;view='add';draw()});$('#listingForm')?.addEventListener('submit',save);$('#search')?.addEventListener('input',e=>{q=e.target.value;draw()});$('#statusFilter')?.addEventListener('change',e=>{filter=e.target.value;draw()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;view=filter==='Crossed Off'?'history':'listings';draw()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;view='add';draw();scrollTo({top:0,behavior:'smooth'})});document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>statusTo(b.dataset.status,b.dataset.next));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(b.dataset.del));}
async function login(){const user=$('#householdUser')?.value||'Stephen';const code=$('#accessCode')?.value?.trim();if(code!==ACCESS_CODE)return say('Access code does not match.');localStorage.setItem('awr_user',user);localStorage.setItem('awr_access_ok','true');if(hasSupabaseConfig)await load();say(`Welcome, ${user}.`);draw();}
function logout(){localStorage.removeItem('awr_access_ok');localStorage.removeItem('awr_user');listings=[];editing=null;view='dashboard';say('Locked.');draw();}
async function save(e){e.preventDefault();const p=read();if(p.status==='Crossed Off'||p.status==='Rejected')p.is_crossed_off=true;try{const f=$('#imageFile')?.files?.[0];if(f)p.image_url=await upload(f);if(!hasSupabaseConfig){editing?listings=listings.map(x=>x.id===editing?{...x,...p}:x):listings.unshift({id:crypto.randomUUID(),...p});}else if(editing){const {error}=await supabase.from('apartments').update(p).eq('id',editing);if(error)throw error;}else{const {error}=await supabase.from('apartments').insert(p);if(error)throw error;}editing=null;view='listings';if(hasSupabaseConfig)await load();say(`Saved by ${currentUser()||'you'}.`);draw();}catch(err){say(err.message||'Save failed.')}}
function read(){return {name:val('name'),area:val('area'),address:val('address'),price:num('price'),bedrooms:num('bedrooms'),bathrooms:num('bathrooms'),sqft:num('sqft'),tier:val('tier'),status:val('status')||'To Call',score:num('score'),notes:val('notes'),verify:val('verify'),source_url:val('source_url'),mls_number:val('mls_number'),is_crossed_off:$('#is_crossed_off')?.checked||false}}
async function upload(file){const path=`listings/${crypto.randomUUID()}.${file.name.split('.').pop()||'jpg'}`;const {error}=await supabase.storage.from('listing-images').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return supabase.storage.from('listing-images').getPublicUrl(path).data.publicUrl;}
async function seed(){if(listings.length)return say('Starter board is already loaded.');try{if(!hasSupabaseConfig)listings=STARTER_LISTINGS.map(x=>({...x,id:crypto.randomUUID()}));else{const {error}=await supabase.from('apartments').insert(STARTER_LISTINGS);if(error)throw error;await load();}say('Starter board loaded.');draw();}catch(e){say(e.message||'Could not load starter board.')}}
async function statusTo(id,next){const p={status:next,is_crossed_off:next==='Crossed Off'||next==='Rejected'};try{if(!hasSupabaseConfig)listings=listings.map(x=>x.id===id?{...x,...p}:x);else{const {error}=await supabase.from('apartments').update(p).eq('id',id);if(error)throw error;await load();}say(next==='Crossed Off'?'Moved to history.':`Marked ${next}.`);draw();}catch(e){say(e.message||'Status update failed.')}}
async function remove(id){const x=listings.find(i=>i.id===id);if(!x||!confirm(`Remove "${x.name}"?`))return;try{if(!hasSupabaseConfig)listings=listings.filter(i=>i.id!==id);else{const {error}=await supabase.from('apartments').delete().eq('id',id);if(error)throw error;await load();}editing=null;if(view==='add')view='listings';say('Listing removed.');draw();}catch(e){say(e.message||'Remove failed.')}}
function val(id){return $(`#${id}`)?.value.trim()||null}function num(id){const x=val(id);return x===null?null:Number(x)}function crossed(x){return !!(x.is_crossed_off||x.status==='Crossed Off'||x.status==='Rejected')}function count(s){return s==='Crossed Off'?listings.filter(crossed).length:listings.filter(x=>x.status===s&&!crossed(x)).length}function match(x){return !q||[x.name,x.area,x.address,x.tier,x.status,x.notes,x.verify,x.mls_number].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase())}function money(v){return v?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v):'Price TBD'}function say(m){toast=m;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast='';draw()},2400);draw()}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
